### ISSUE TITLE
 Barbados (BB): "state_name_type" should be "locality_name_type" ?

### ISSUE THREAD

**Issue by ehom** [googlei18n/libaddressinput#120]
Not sure if this is an issue. 

Here's my observation:

BB has state_name_type but doesn't have fmt. 

So, does BB uses ZZ's fmt which doesn't have "%S" ???

According to the [global sourcebook for intl data management](http://www.grcdi.nl/gsb/barbados.html), parish is at the same level as city.

So, should "state_name_type" be "locality_name_type" then?

----

> https://chromium-i18n.appspot.com/ssl-address/data/BB
```json
{
    "key": "BB", "zipex": "BB23026,BB22025", "name": "BARBADOS", "zip": "BB\\d{5}", 

    "state_name_type": "parish", 

    "posturl": "http://barbadospostal.com/zipcodes.html", "id": "data/BB"
}
```

> https://chromium-i18n.appspot.com/ssl-address/data/ZZ

```json
{
    "upper": "C", "sublocality_name_type": "suburb",  "zip_name_type": "postal", 

    "fmt": "%N%n%O%n%A%n%C", 

    "state_name_type": "province", 

    "locality_name_type": "city", 
    "require": "AC", "id": "data/ZZ"
}
```

----

Other Reference: [UPU.int](http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/brbEn.pdf)

**Comment by lararennie** [comment]
This is indeed an inconsistency; either state name type should be removed,
or it should have its own fmt string... However I think the problem is that
Chromium is out of date:
Notice in RegionDataConstants
<https://github.com/googlei18n/libaddressinput/blob/master/common/src/main/java/com/google/i18n/addressinput/common/RegionDataConstants.java>
the following:
map.put("BB", "{\"name\":\"BARBADOS\",\"fmt\":\"%N%n%O%n%A%n%C, %S
%Z\",\"state_name_type\":\"parish\"}");

Let's see if we can get them to update.

9. feb. 2017 9.54 a.m. skrev "ehom" <notifications@github.com>:

**Comment by sockix** [comment]
Thank you for the heads up.  

Chromium has since been updated and 'BB' now shows as a fmt with '%S' present.

Cheers!
