### ISSUE TITLE
Mozambique

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#58]
The dataset has an entry for Mozambique:
https://i18napis.appspot.com/address/data/MZ
This entry contains the postal code validation pattern, and example postal codes, but declares no fields, so the fallback ZZ format fields are used instead, but they don't include a postal code field at all.

So, the entry at least needs to have a list of fields that includes the postal code and administrative area.
Next, it should include the Mozambique provinces, as listed on:
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/mozEn.pdf

**Comment by sockix** [comment]
The first part of this issue is actually no longer a problem... we have specified a 'fmt' for MZ which includes the postal code.

In the form, we currently display 'locality', and not 'administrative area', and thus we do not display an explicit list of values.  We will look into whether it's helpful and/or necessary to also include the administrative area selection as well.

**Comment by bojanz** [comment]
Administrative areas for MZ have been added.
